# Site settings
title: Gaussian Process and Uncertainty Quantification Summer School, 2019
author:
  email:
description: > # this means to ignore newlines until "baseurl:"
  Gaussian Process Summer School
baseurl: "/gpss19" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: sheffieldmlnet
github_username:  gpschool
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: gpss


youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: gpss19

markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"
banner:

analytics:
 google:
   tracking_id: UA-62991754-1# Google tracking ID if applicable

youtube:
  height: 315
  width: 560

conference:
  draft: false # set to True if the programme is draft only.
  hide_tentative: true
  hosts:
  short_name: GPSS
  full_name:  Gaussian Process and Uncertainty Quantification Summer School
  venue: Pam Liversidge Building, PLB-E05, The University of Sheffield
  location: Sheffield, UK
  name: Gaussian Process Summer School
  year: 2019
  month: September
  dates:
  - 2019-09-09
  - 2019-09-10
  - 2019-09-11
  - 2019-09-12
  chairs:
  - type: Organizers
    people:
    - {given: Mauricio, family: Alvarez, url: "https://maalvarezl.github.io/", institute: University of Sheffield}
    - {given: Javier, family: Gonzalez, url: "http://javiergonzalezh.github.io/", institute: Amazon Cambridge}
    - {given: Neil D., family: Lawrence, url: "http://inverseprobability.com", institute: University of Sheffield}
    - {given: Richard, family: Wilkinson, url: "http://r-wilkinson.staff.shef.ac.uk/", institute: University of Sheffield}
    - {given: Wil, family: Ward, url: "https://wilocw.github.io/", institute: University of Sheffield}
    - {given: Michael T., family: Smith, url: "http://www.michaeltsmith.org.uk/", institute: University of Sheffield}
    - {given: Fariba, family: Yousefi, url: "https://www.dcs.shef.ac.uk/cgi-intranet/public/makeperson?F.Yousefi", institute: University of Sheffield}
    - {given: Juan Jose, family: Giraldo Gutierrez, url: "http://www.dcs.shef.ac.uk/cgi-intranet/public/makeperson?J.Giraldo_Gutierrez", institute: University of Sheffield}
    - {given: "", family: Sheffield Machine Learning Group, url: "https://www.sheffield.ac.uk/dcs/research/groups/machine-learning"}

previous_meeting:
  name: Past Meetings
  url: "http://gpss.cc/past_meetings.html"

map:
  show: true
  mapbox:
    latitude: 53.385396 # latitude of map center
    longitude: -1.472726 # longitude of map center
    map_id1: maalvarezl # mapbox id1
    map_id2: cj6hz56fb4q9l2rpajqiqw5ki # mapbox id2
    fresh: true
    title: false
    access_token: pk.eyJ1IjoibWFhbHZhcmV6bCIsImEiOiJjajY1Nmo1b3gxb2d2Mndub2dyeDNsa2IzIn0.qLCz36sKjWARW8EBSy2fAQ # mapbox access token
    zoom_level: 14.5
    width: 100%
    height: 500px
